### ISSUE TITLE
boost::hash removed

### ISSUE THREAD

**Issue by joaquintides** [martinus/map_benchmark#15]
Hi, 1a6323c6607e37767749ae83ecaa4f54cf9b9159 removes `boost::hash` because, allegedly, "it's exactly the same as `std::hash`". But I don't think is is the case at all, unless I'm missing something in context.

Thank you!

**Comment by martinus** [comment]
For `uint64_t` input it produces exactly the same results as std::hash, just the identity. But you are right, its probably different for strings. Or am I missing something else?

**Comment by joaquintides** [comment]
Yes, for integrals, `boost::hash` is just the identity. For it is different to `std::hash` for strings, which are also tested in your benchmarks.

**Comment by martinus** [comment]
I'll add it back

**Comment by martinus** [comment]
I'll keep it open until I actually add it back so I don't forget :slightly_smiling_face:

**Comment by martinus** [comment]
its back
