### ISSUE TITLE
Request for inclusion of Boost.MultiIndex

### ISSUE THREAD

**Issue by joaquintides** [martinus/map_benchmark#2]
I'd very much like to see Boost.MultiIndex included in this benchmark. As it happens, the library provides a set-like interface rather than that of a map, but the latter can easily be emulated as follows:

    #pragma once

    #include "Hash.h"
    #include <boost/multi_index_container.hpp>
    #include <boost/multi_index/hashed_index.hpp>
    #include <boost/multi_index/member.hpp>
    #include <utility>
    
    static const char* MapName = "boost::multi_index::hashed_unique";
    
    template <class T1, class T2>
    struct MapElement
    {
        using first_type = T1;
        using second_type = T2;
        
        template<class Q1>
        MapElement(Q1&& first):
            first{std::forward<Q1>(first)},
            second{}
            {}
    
        template<class Q1, class Q2>
        MapElement(Q1&& first, Q2&& second):
            first{std::forward<Q1>(first)},
            second{std::forward<Q2>(second)}
            {}
        
        T1         first;
        mutable T2 second;
    };
    
    template <class Key, class Val>
    using MapBase = boost::multi_index_container<
        MapElement<Key, Val>,
        boost::multi_index::indexed_by<
            boost::multi_index::hashed_unique<
                boost::multi_index::member<
                    MapElement<Key, Val>, Key, &MapElement<Key, Val>::first
                >,
                Hash<Key>
            >
        >
    >;
    
    template <class Key, class Val>
    struct Map: MapBase<Key, Val>
    {
      using super = MapBase<Key, Val>;
      using super::super;
      
      template <class K>
      Val& operator[](K&& key){
          return this->emplace(std::forward<K>(key)).first->second; 
      }
    };

**Comment by martinus** [comment]
Thanks for this! I've added it to the benchmark in comit https://github.com/martinus/map_benchmark/commit/f97c368405e889bb4c29854fecdc088c77be258f
