### ISSUE TITLE
Could you add the results please

### ISSUE THREAD

**Issue by billyquith** [martinus/map_benchmark#5]
Adding some results in the readme or on the wiki would be great. Perhaps be useful as a reference for machines with different specs.

**Comment by ktprime** [comment]
I also think it's a good ideal.

**Comment by martinus** [comment]
I'm still working on results. A full run of the benchmark has already finished, I just need to create some nice pages from it.

**Comment by felixguendling** [comment]
I am also interested in a results table and graphic! 👍 
I think this is a good and comprehensive style to present the results:
https://tessil.github.io/2016/08/29/benchmark-hopscotch-map.html

**Comment by martinus** [comment]
I have the results ready, just need to finish my writeup! I hope to finish it this week

**Comment by felixguendling** [comment]
Thank you! Looking forward to your article! :-)

**Comment by martinus** [comment]
Finally, I have my results available here: https://martin.ankerl.com/2019/04/01/hashmap-benchmarks-01-overview/
