### ISSUE TITLE
Add  a copy benchmark

### ISSUE THREAD

**Issue by martinus** [martinus/map_benchmark#8]
See this discussion:
https://www.reddit.com/r/cpp/comments/bg4z2l/big_hashmap_comparison/eljd0ku/

Add benchmark to 
* copy map by sequentially iterating it
* copy map by using copy ctor

* copy almost empty map?
* copy with high fill factor

**Comment by rljacobson** [comment]
Very nice work!

**Comment by martinus** [comment]
done, 3 years later :-)
